import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import Card from '../components/blogpost_card';
import Category from '../components/category';
import Latest from '../components/latest';

//const posts_num = 0;

export default function Home({ blog_posts }) {

  return (
    <div className=' bg-slate-100'>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        <div className='grid grid-cols-12 mx-auto w-full'>
          <div className='col-span-2 mx-2'>
            <div className='lg:sticky relative top-8 w-full'>
              <div className='rounded-md shadow-sm shadow-black p-4 my-12 bg-white'>
                <h1 className='text-3xl text-center'>Categories</h1>
                <Category />
              </div>
            </div>
          </div >

          <div className='col-span-7 mr-4'>
            <div className=" w-12/12  break-words ">
              {blog_posts.map(data => {
                return (
                  <div key={data.id} className="">
                    <Card data={data} />
                  </div>
                )
              })}
            </div>
            {/*
              <div className=' mx-auto'>
                <button className=' p-2 my-4 rounded-sm bg-blue-600 hover:bg-blue-500 text-center mx-auto' onClick={() => (posts_num += 3, console.log(posts_num))}>See more!</button>
              </div>
            */}
          </div>

          <div className=' col-span-3 mx-2'>
            <div className='lg:sticky relative top-4 w-full'>
              <div className='rounded-md shadow-sm shadow-black p-4 my-12 bg-white'>
                <h1 className='text-3xl text-center'>Latest posts</h1>
                <Latest />
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        Maanas Mahato
      </footer>
    </div>
  )
}

export const getServerSideProps = async () => {
  const res_posts = await axios.get("http://localhost:1337/api/posts?fields=title,meta_desc,createdAt")
  const posts_data = await res_posts.data

  return {
    props: {
      blog_posts: posts_data.data, //.slice(0, 3 /* + posts_num)*/),
    }
  }
}